//! MCU (ESP32, STM32, etc.) code generation
//!
//! Generates embedded Rust firmware using embassy or esp-idf-hal

use crate::config::*;
use crate::error::{OasisError, Result};
use std::path::Path;
use std::fs;

/// Generate MCU firmware project
pub fn generate(config: &DeviceConfig, output_dir: &Path) -> Result<()> {
    tracing::info!("Generating MCU firmware for {}", config.device.id);
    
    // Create output directory structure
    let src_dir = output_dir.join("src");
    fs::create_dir_all(&src_dir)?;
    
    // Generate Cargo.toml
    generate_cargo_toml(config, output_dir)?;
    
    // Generate main.rs
    generate_main_rs(config, &src_dir)?;
    
    // Generate sensor modules
    generate_sensors_module(config, &src_dir)?;
    
    // Generate actuator modules
    generate_actuators_module(config, &src_dir)?;
    
    // Generate control loop module
    generate_control_module(config, &src_dir)?;
    
    // Generate communication module
    generate_comms_module(config, &src_dir)?;
    
    // Generate build.rs if needed
    generate_build_rs(config, output_dir)?;
    
    // Generate .cargo/config.toml
    generate_cargo_config(config, output_dir)?;
    
    tracing::info!("MCU firmware generated at {:?}", output_dir);
    Ok(())
}

fn generate_cargo_toml(config: &DeviceConfig, output_dir: &Path) -> Result<()> {
    let board = &config.device.board.model;
    
    // Determine HAL crate based on board
    let (hal_crate, hal_features) = match board.as_str() {
        "esp32_devkit" | "esp32_c3" | "esp32_s3" => {
            ("esp-idf-hal", vec!["embassy"])
        }
        "stm32f103" => ("stm32f1xx-hal", vec!["stm32f103", "rt"]),
        "stm32f411" => ("stm32f4xx-hal", vec!["stm32f411", "rt"]),
        "teensy_40" | "teensy_41" => ("teensy4-bsp", vec![]),
        _ => return Err(OasisError::UnsupportedBoard(board.clone())),
    };
    
    let content = format!(r#"[package]
name = "{device_id}-firmware"
version = "0.1.0"
edition = "2021"

[dependencies]
# HAL
{hal_crate} = {{ version = "*", features = {hal_features:?} }}

# Async runtime
embassy-executor = {{ version = "0.5", features = ["arch-xtensa", "executor-thread"] }}
embassy-time = "0.3"
embassy-sync = "0.5"

# Serialization
serde = {{ version = "1.0", default-features = false, features = ["derive"] }}
postcard = {{ version = "1.0", features = ["alloc"] }}

# Logging
defmt = "0.3"
defmt-rtt = "0.4"

# MQTT (if enabled)
{mqtt_dep}

# Error handling
embedded-hal = "1.0"

[profile.release]
opt-level = "s"
lto = true
debug = false

[profile.dev]
opt-level = 1
debug = true
"#,
        device_id = config.device.id.replace('-', "_"),
        hal_crate = hal_crate,
        hal_features = hal_features,
        mqtt_dep = if needs_mqtt(config) {
            r#"embedded-mqtt = "0.1""#
        } else {
            "# embedded-mqtt = \"0.1\"  # Uncomment if MQTT needed"
        },
    );
    
    fs::write(output_dir.join("Cargo.toml"), content)?;
    Ok(())
}

fn generate_main_rs(config: &DeviceConfig, src_dir: &Path) -> Result<()> {
    let content = format!(r#"//! {device_name} Firmware
//! 
//! Auto-generated by oasis-build from device.yaml
//! Device ID: {device_id}

#![no_std]
#![no_main]

mod sensors;
mod actuators;
mod control;
mod comms;

use embassy_executor::Spawner;
use defmt::*;
use defmt_rtt as _;

// Device configuration (compiled in)
const DEVICE_ID: &str = "{device_id}";

#[embassy_executor::main]
async fn main(spawner: Spawner) {{
    info!("Starting {{}} firmware", DEVICE_ID);
    
    // Initialize hardware
    let peripherals = embassy_hal::init(Default::default());
    
    // Initialize sensors
    let sensors = sensors::init(&peripherals);
    info!("Initialized {{}} sensors", sensors.len());
    
    // Initialize actuators
    let actuators = actuators::init(&peripherals);
    info!("Initialized {{}} actuators", actuators.len());
    
    // Initialize communication
    comms::init(&spawner, &peripherals).await;
    
    // Spawn sensor reading tasks
    for sensor in sensors {{
        spawner.spawn(sensors::read_task(sensor)).unwrap();
    }}
    
    // Spawn control loop tasks
    {control_spawns}
    
    // Spawn communication task
    spawner.spawn(comms::publish_task()).unwrap();
    
    info!("{{}} firmware running", DEVICE_ID);
    
    // Main loop - handle watchdog
    loop {{
        embassy_time::Timer::after_millis(1000).await;
        // Feed watchdog here
    }}
}}

#[panic_handler]
fn panic(info: &core::panic::PanicInfo) -> ! {{
    defmt::error!("Panic: {{}}", defmt::Debug2Format(info));
    loop {{}}
}}
"#,
        device_name = config.device.name,
        device_id = config.device.id,
        control_spawns = generate_control_spawns(config),
    );
    
    fs::write(src_dir.join("main.rs"), content)?;
    Ok(())
}

fn generate_control_spawns(config: &DeviceConfig) -> String {
    config.control_loops.iter()
        .map(|ctrl| format!(
            "spawner.spawn(control::{}()).unwrap();",
            ctrl.name.replace('-', "_")
        ))
        .collect::<Vec<_>>()
        .join("\n    ")
}

fn generate_sensors_module(config: &DeviceConfig, src_dir: &Path) -> Result<()> {
    let sensor_inits: Vec<String> = config.sensors.iter()
        .map(|s| generate_sensor_init(s))
        .collect();
    
    let content = format!(r#"//! Sensor drivers and reading tasks

use embassy_sync::channel::Channel;
use embassy_time::{{Duration, Timer}};
use defmt::*;

/// Sensor reading channel (sensor_name, measurement_name, value)
pub static READINGS: Channel<CriticalSectionRawMutex, SensorReading, 32> = Channel::new();

#[derive(Clone, Debug)]
pub struct SensorReading {{
    pub sensor: &'static str,
    pub measurement: &'static str,
    pub value: f32,
    pub timestamp_ms: u64,
}}

pub struct Sensor {{
    pub name: &'static str,
    pub interval_ms: u32,
    // Add sensor-specific fields
}}

pub fn init(peripherals: &Peripherals) -> Vec<Sensor> {{
    let mut sensors = Vec::new();
    
    {sensor_inits}
    
    sensors
}}

#[embassy_executor::task]
pub async fn read_task(sensor: Sensor) {{
    loop {{
        // Read sensor
        let reading = read_sensor(&sensor).await;
        
        // Send to channel
        READINGS.send(reading).await;
        
        // Wait for next interval
        Timer::after(Duration::from_millis(sensor.interval_ms as u64)).await;
    }}
}}

async fn read_sensor(sensor: &Sensor) -> SensorReading {{
    // TODO: Implement actual sensor reading based on type
    SensorReading {{
        sensor: sensor.name,
        measurement: "value",
        value: 0.0,
        timestamp_ms: embassy_time::Instant::now().as_millis(),
    }}
}}
"#,
        sensor_inits = sensor_inits.join("\n    "),
    );
    
    fs::write(src_dir.join("sensors.rs"), content)?;
    Ok(())
}

fn generate_sensor_init(sensor: &Sensor) -> String {
    format!(r#"// {name}: {sensor_type:?}
    sensors.push(Sensor {{
        name: "{name}",
        interval_ms: {interval},
    }});"#,
        name = sensor.name,
        sensor_type = sensor.sensor_type,
        interval = sensor.sampling.interval_ms,
    )
}

fn generate_actuators_module(config: &DeviceConfig, src_dir: &Path) -> Result<()> {
    let actuator_inits: Vec<String> = config.actuators.iter()
        .map(|a| generate_actuator_init(a))
        .collect();
    
    let content = format!(r#"//! Actuator drivers and control

use embassy_sync::channel::Channel;
use defmt::*;

/// Command channel for actuators
pub static COMMANDS: Channel<CriticalSectionRawMutex, ActuatorCommand, 16> = Channel::new();

#[derive(Clone, Debug)]
pub struct ActuatorCommand {{
    pub actuator: &'static str,
    pub action: ActuatorAction,
}}

#[derive(Clone, Debug)]
pub enum ActuatorAction {{
    SetState(bool),
    SetValue(u16),
}}

pub struct Actuator {{
    pub name: &'static str,
    // Add actuator-specific fields
}}

pub fn init(peripherals: &Peripherals) -> Vec<Actuator> {{
    let mut actuators = Vec::new();
    
    {actuator_inits}
    
    actuators
}}

pub fn set_state(name: &str, state: bool) {{
    // TODO: Find actuator and set state
    info!("Set {{}} to {{}}", name, state);
}}

pub fn set_value(name: &str, value: u16) {{
    // TODO: Find actuator and set value
    info!("Set {{}} to {{}}", name, value);
}}
"#,
        actuator_inits = actuator_inits.join("\n    "),
    );
    
    fs::write(src_dir.join("actuators.rs"), content)?;
    Ok(())
}

fn generate_actuator_init(actuator: &Actuator) -> String {
    format!(r#"// {name}: {actuator_type:?}
    actuators.push(Actuator {{
        name: "{name}",
    }});"#,
        name = actuator.name,
        actuator_type = actuator.actuator_type,
    )
}

fn generate_control_module(config: &DeviceConfig, src_dir: &Path) -> Result<()> {
    let control_tasks: Vec<String> = config.control_loops.iter()
        .map(|ctrl| generate_control_task(ctrl))
        .collect();
    
    let content = format!(r#"//! Control loop implementations

use embassy_time::{{Duration, Timer}};
use crate::sensors::READINGS;
use crate::actuators;
use defmt::*;

{control_tasks}
"#,
        control_tasks = control_tasks.join("\n\n"),
    );
    
    fs::write(src_dir.join("control.rs"), content)?;
    Ok(())
}

fn generate_control_task(ctrl: &ControlLoop) -> String {
    let task_name = ctrl.name.replace('-', "_");
    
    match ctrl.loop_type {
        ControlLoopType::Threshold => {
            let threshold = ctrl.threshold.as_ref().unwrap();
            format!(r#"#[embassy_executor::task]
pub async fn {task_name}() {{
    const SETPOINT: f32 = {setpoint};
    const HYSTERESIS: f32 = {hysteresis};
    const INPUT_SENSOR: &str = "{sensor}";
    const INPUT_MEASUREMENT: &str = "{measurement}";
    const OUTPUT_ACTUATOR: &str = "{actuator}";
    
    let mut state = false;
    
    loop {{
        // Get latest reading for our sensor
        let reading = READINGS.receive().await;
        
        if reading.sensor == INPUT_SENSOR && reading.measurement == INPUT_MEASUREMENT {{
            let value = reading.value;
            
            // Threshold with hysteresis
            let new_state = match "{direction}" {{
                "cool" => value > SETPOINT + HYSTERESIS,
                "heat" => value < SETPOINT - HYSTERESIS,
                _ => state,
            }};
            
            if new_state != state {{
                state = new_state;
                actuators::set_state(OUTPUT_ACTUATOR, state);
                info!("{{}} -> {{}}", OUTPUT_ACTUATOR, state);
            }}
        }}
    }}
}}"#,
                task_name = task_name,
                setpoint = threshold.setpoint,
                hysteresis = threshold.hysteresis,
                sensor = ctrl.input.sensor,
                measurement = ctrl.input.measurement,
                actuator = ctrl.output.actuator,
                direction = format!("{:?}", threshold.direction).to_lowercase(),
            )
        }
        ControlLoopType::Pid => {
            let pid = ctrl.pid.as_ref().unwrap();
            format!(r#"#[embassy_executor::task]
pub async fn {task_name}() {{
    const KP: f32 = {kp};
    const KI: f32 = {ki};
    const KD: f32 = {kd};
    const SETPOINT: f32 = {setpoint};
    const OUTPUT_MIN: f32 = {output_min};
    const OUTPUT_MAX: f32 = {output_max};
    const SAMPLE_TIME_MS: u32 = {sample_time};
    
    let mut integral: f32 = 0.0;
    let mut prev_error: f32 = 0.0;
    
    loop {{
        let reading = READINGS.receive().await;
        
        if reading.sensor == "{sensor}" && reading.measurement == "{measurement}" {{
            let error = SETPOINT - reading.value;
            
            // PID calculation
            integral += error * (SAMPLE_TIME_MS as f32 / 1000.0);
            let derivative = (error - prev_error) / (SAMPLE_TIME_MS as f32 / 1000.0);
            prev_error = error;
            
            let mut output = KP * error + KI * integral + KD * derivative;
            output = output.clamp(OUTPUT_MIN, OUTPUT_MAX);
            
            actuators::set_value("{actuator}", output as u16);
        }}
        
        Timer::after(Duration::from_millis(SAMPLE_TIME_MS as u64)).await;
    }}
}}"#,
                task_name = task_name,
                kp = pid.kp,
                ki = pid.ki,
                kd = pid.kd,
                setpoint = pid.setpoint,
                output_min = pid.output_min,
                output_max = pid.output_max,
                sample_time = pid.sample_time_ms,
                sensor = ctrl.input.sensor,
                measurement = ctrl.input.measurement,
                actuator = ctrl.output.actuator,
            )
        }
        _ => format!(r#"#[embassy_executor::task]
pub async fn {task_name}() {{
    // TODO: Implement {loop_type:?} control loop
    loop {{
        Timer::after(Duration::from_secs(1)).await;
    }}
}}"#, task_name = task_name, loop_type = ctrl.loop_type),
    }
}

fn generate_comms_module(config: &DeviceConfig, src_dir: &Path) -> Result<()> {
    let content = format!(r#"//! Communication (MQTT/HTTPS) module

use embassy_time::{{Duration, Timer}};
use crate::sensors::READINGS;
use defmt::*;

const DEVICE_ID: &str = "{device_id}";
{mqtt_config}
{https_config}

pub async fn init(spawner: &Spawner, peripherals: &Peripherals) {{
    // TODO: Initialize WiFi and connect
    info!("Initializing communications for {{}}", DEVICE_ID);
}}

#[embassy_executor::task]
pub async fn publish_task() {{
    loop {{
        // Collect readings and publish
        let reading = READINGS.receive().await;
        
        // TODO: Publish via MQTT or batch for HTTPS
        info!("Publish: {{}}:{{}} = {{}}", reading.sensor, reading.measurement, reading.value);
        
        Timer::after(Duration::from_millis({publish_interval})).await;
    }}
}}
"#,
        device_id = config.device.id,
        mqtt_config = generate_mqtt_config(config),
        https_config = generate_https_config(config),
        publish_interval = config.data_publishing
            .as_ref()
            .and_then(|dp| dp.mqtt.as_ref())
            .map(|m| m.publish_interval_ms)
            .unwrap_or(5000),
    );
    
    fs::write(src_dir.join("comms.rs"), content)?;
    Ok(())
}

fn generate_mqtt_config(config: &DeviceConfig) -> String {
    if let Some(mqtt) = config.connectivity.mqtt.as_ref() {
        format!(r#"
const MQTT_BROKER: &str = "{}";
const MQTT_PORT: u16 = {};
const MQTT_USE_TLS: bool = {};"#,
            mqtt.broker, mqtt.port, mqtt.use_tls)
    } else {
        String::new()
    }
}

fn generate_https_config(config: &DeviceConfig) -> String {
    if let Some(https) = config.connectivity.https.as_ref() {
        format!(r#"
const HTTPS_ENDPOINT: &str = "{}";"#, https.endpoint)
    } else {
        String::new()
    }
}

fn generate_build_rs(_config: &DeviceConfig, output_dir: &Path) -> Result<()> {
    let content = r#"//! Build script for firmware

fn main() {
    // Link scripts, etc.
    println!("cargo:rerun-if-changed=build.rs");
}
"#;
    
    fs::write(output_dir.join("build.rs"), content)?;
    Ok(())
}

fn generate_cargo_config(config: &DeviceConfig, output_dir: &Path) -> Result<()> {
    let cargo_dir = output_dir.join(".cargo");
    fs::create_dir_all(&cargo_dir)?;
    
    let target = match config.device.board.model.as_str() {
        "esp32_devkit" => "xtensa-esp32-none-elf",
        "esp32_c3" => "riscv32imc-unknown-none-elf",
        "esp32_s3" => "xtensa-esp32s3-none-elf",
        "stm32f103" => "thumbv7m-none-eabi",
        "stm32f411" => "thumbv7em-none-eabihf",
        _ => "thumbv7em-none-eabihf",
    };
    
    let content = format!(r#"[build]
target = "{target}"

[target.{target}]
runner = "probe-rs run --chip auto"

[env]
DEFMT_LOG = "info"
"#, target = target);
    
    fs::write(cargo_dir.join("config.toml"), content)?;
    Ok(())
}

fn needs_mqtt(config: &DeviceConfig) -> bool {
    matches!(config.connectivity.mode, 
        ConnectivityMode::DirectMqtt | ConnectivityMode::Hybrid)
}
