//! Raspberry Pi code generation
//!
//! Generates a Rust supervisor daemon for RPi platforms

use crate::config::*;
use crate::error::Result;
use std::path::Path;
use std::fs;

/// Generate RPi supervisor project
pub fn generate(config: &DeviceConfig, output_dir: &Path) -> Result<()> {
    tracing::info!("Generating RPi supervisor for {}", config.device.id);
    
    // Create output directory structure
    let src_dir = output_dir.join("src");
    fs::create_dir_all(&src_dir)?;
    
    // Generate Cargo.toml
    generate_cargo_toml(config, output_dir)?;
    
    // Generate main.rs
    generate_main_rs(config, &src_dir)?;
    
    // Generate config module
    generate_config_module(config, &src_dir)?;
    
    // Generate sensors module
    generate_sensors_module(config, &src_dir)?;
    
    // Generate actuators module
    generate_actuators_module(config, &src_dir)?;
    
    // Generate MQTT module
    generate_mqtt_module(config, &src_dir)?;
    
    // Generate serial bridge module (for gateway mode)
    generate_serial_module(config, &src_dir)?;
    
    // Generate systemd service file
    generate_systemd_service(config, output_dir)?;
    
    tracing::info!("RPi supervisor generated at {:?}", output_dir);
    Ok(())
}

fn generate_cargo_toml(config: &DeviceConfig, output_dir: &Path) -> Result<()> {
    let content = format!(r#"[package]
name = "{device_id}-supervisor"
version = "0.1.0"
edition = "2021"

[dependencies]
# Async runtime
tokio = {{ version = "1.36", features = ["full"] }}

# GPIO/Hardware
rppal = {{ version = "0.17", features = ["hal"] }}

# MQTT
rumqttc = "0.24"

# HTTP client
reqwest = {{ version = "0.11", features = ["json", "rustls-tls"], default-features = false }}

# Serial communication
tokio-serial = "5.4"

# Serialization
serde = {{ version = "1.0", features = ["derive"] }}
serde_json = "1.0"
postcard = "1.0"

# Logging
tracing = "0.1"
tracing-subscriber = {{ version = "0.3", features = ["env-filter"] }}

# Error handling
anyhow = "1.0"
thiserror = "1.0"

# Config
config = "0.14"
dotenvy = "0.15"

# Time
chrono = "0.4"

[profile.release]
opt-level = 3
lto = true
"#,
        device_id = config.device.id.replace('-', "_"),
    );
    
    fs::write(output_dir.join("Cargo.toml"), content)?;
    Ok(())
}

fn generate_main_rs(config: &DeviceConfig, src_dir: &Path) -> Result<()> {
    let content = format!(r#"//! {device_name} Supervisor
//!
//! Auto-generated by oasis-build from device.yaml
//! Device ID: {device_id}

mod config;
mod sensors;
mod actuators;
mod mqtt;
mod serial;

use anyhow::Result;
use tracing::{{info, Level}};
use tracing_subscriber::EnvFilter;

#[tokio::main]
async fn main() -> Result<()> {{
    // Initialize logging
    tracing_subscriber::fmt()
        .with_env_filter(
            EnvFilter::from_default_env()
                .add_directive(Level::INFO.into())
        )
        .init();
    
    info!("Starting {device_id} supervisor");
    
    // Load configuration
    let config = config::load()?;
    info!("Loaded configuration for device: {{}}", config.device_id);
    
    // Initialize hardware
    let gpio = rppal::gpio::Gpio::new()?;
    
    // Initialize sensors
    let sensors = sensors::init(&gpio, &config).await?;
    info!("Initialized {{}} sensors", sensors.len());
    
    // Initialize actuators
    let actuators = actuators::init(&gpio, &config).await?;
    info!("Initialized {{}} actuators", actuators.len());
    
    // Start MQTT connection
    let mqtt_handle = mqtt::start(&config).await?;
    
    // Start serial bridge (if gateway mode)
    {serial_init}
    
    // Run the supervisor
    tokio::select! {{
        res = sensors::run_all(sensors, mqtt_handle.clone()) => {{
            if let Err(e) = res {{
                tracing::error!("Sensor task failed: {{:?}}", e);
            }}
        }}
        res = mqtt::run(mqtt_handle) => {{
            if let Err(e) = res {{
                tracing::error!("MQTT task failed: {{:?}}", e);
            }}
        }}
        _ = tokio::signal::ctrl_c() => {{
            info!("Shutdown signal received");
        }}
    }}
    
    info!("{device_id} supervisor stopped");
    Ok(())
}}
"#,
        device_name = config.device.name,
        device_id = config.device.id,
        serial_init = if matches!(config.connectivity.mode, ConnectivityMode::Hybrid | ConnectivityMode::SerialGateway) {
            r#"let serial_handle = serial::start(&config).await?;
    tokio::spawn(serial::run(serial_handle, mqtt_handle.clone()));"#
        } else {
            "// Serial bridge not enabled for this connectivity mode"
        },
    );
    
    fs::write(src_dir.join("main.rs"), content)?;
    Ok(())
}

fn generate_config_module(config: &DeviceConfig, src_dir: &Path) -> Result<()> {
    let content = format!(r#"//! Configuration loading

use anyhow::Result;
use serde::Deserialize;

#[derive(Debug, Deserialize)]
pub struct AppConfig {{
    pub device_id: String,
    pub mqtt: MqttConfig,
    pub https: Option<HttpsConfig>,
    pub serial: Option<SerialConfig>,
}}

#[derive(Debug, Deserialize)]
pub struct MqttConfig {{
    pub broker: String,
    pub port: u16,
    pub use_tls: bool,
    pub telemetry_topic: String,
    pub cmd_topic: String,
}}

#[derive(Debug, Deserialize)]
pub struct HttpsConfig {{
    pub endpoint: String,
    pub batch_interval_s: u32,
}}

#[derive(Debug, Deserialize)]
pub struct SerialConfig {{
    pub port: String,
    pub baud_rate: u32,
}}

pub fn load() -> Result<AppConfig> {{
    // Load .env file if present
    dotenvy::dotenv().ok();
    
    // Build configuration
    let config = AppConfig {{
        device_id: "{device_id}".into(),
        mqtt: MqttConfig {{
            broker: std::env::var("MQTT_BROKER").unwrap_or_else(|_| "{mqtt_broker}".into()),
            port: std::env::var("MQTT_PORT")
                .ok()
                .and_then(|s| s.parse().ok())
                .unwrap_or({mqtt_port}),
            use_tls: {mqtt_tls},
            telemetry_topic: "oasis/devices/{device_id}/telemetry".into(),
            cmd_topic: "oasis/devices/{device_id}/cmd".into(),
        }},
        https: {https_config},
        serial: {serial_config},
    }};
    
    Ok(config)
}}
"#,
        device_id = config.device.id,
        mqtt_broker = config.connectivity.mqtt.as_ref().map(|m| m.broker.as_str()).unwrap_or("localhost"),
        mqtt_port = config.connectivity.mqtt.as_ref().map(|m| m.port).unwrap_or(8883),
        mqtt_tls = config.connectivity.mqtt.as_ref().map(|m| m.use_tls).unwrap_or(true),
        https_config = if config.connectivity.https.is_some() {
            format!(r#"Some(HttpsConfig {{
            endpoint: "{}".into(),
            batch_interval_s: {},
        }})"#, 
                config.connectivity.https.as_ref().unwrap().endpoint,
                config.data_publishing.as_ref()
                    .and_then(|dp| dp.https.as_ref())
                    .map(|h| h.batch_interval_s)
                    .unwrap_or(60)
            )
        } else {
            "None".into()
        },
        serial_config = if config.connectivity.serial.is_some() {
            format!(r#"Some(SerialConfig {{
            port: "/dev/ttyUSB0".into(),
            baud_rate: {},
        }})"#, config.connectivity.serial.as_ref().unwrap().baud_rate)
        } else {
            "None".into()
        },
    );
    
    fs::write(src_dir.join("config.rs"), content)?;
    Ok(())
}

fn generate_sensors_module(_config: &DeviceConfig, src_dir: &Path) -> Result<()> {
    let content = r#"//! Sensor drivers for RPi GPIO/I2C/SPI

use anyhow::Result;
use rppal::gpio::Gpio;
use tokio::sync::mpsc;
use std::sync::Arc;

pub struct SensorHandle {
    pub name: String,
    // Add sensor-specific fields
}

pub async fn init(gpio: &Gpio, config: &super::config::AppConfig) -> Result<Vec<SensorHandle>> {
    let mut sensors = Vec::new();
    
    // TODO: Initialize sensors based on config
    
    Ok(sensors)
}

pub async fn run_all(
    sensors: Vec<SensorHandle>,
    mqtt_tx: Arc<super::mqtt::MqttHandle>,
) -> Result<()> {
    // Run sensor reading loops
    let mut handles = Vec::new();
    
    for sensor in sensors {
        let mqtt = mqtt_tx.clone();
        handles.push(tokio::spawn(async move {
            loop {
                // Read sensor
                // Send via MQTT
                tokio::time::sleep(tokio::time::Duration::from_secs(5)).await;
            }
        }));
    }
    
    for handle in handles {
        handle.await?;
    }
    
    Ok(())
}
"#;
    
    fs::write(src_dir.join("sensors.rs"), content)?;
    Ok(())
}

fn generate_actuators_module(_config: &DeviceConfig, src_dir: &Path) -> Result<()> {
    let content = r#"//! Actuator drivers for RPi GPIO

use anyhow::Result;
use rppal::gpio::Gpio;

pub struct ActuatorHandle {
    pub name: String,
    // Add actuator-specific fields
}

pub async fn init(gpio: &Gpio, config: &super::config::AppConfig) -> Result<Vec<ActuatorHandle>> {
    let mut actuators = Vec::new();
    
    // TODO: Initialize actuators based on config
    
    Ok(actuators)
}

pub fn set_state(name: &str, state: bool) -> Result<()> {
    tracing::info!("Set {} to {}", name, state);
    // TODO: Implement
    Ok(())
}

pub fn set_value(name: &str, value: u16) -> Result<()> {
    tracing::info!("Set {} to {}", name, value);
    // TODO: Implement
    Ok(())
}
"#;
    
    fs::write(src_dir.join("actuators.rs"), content)?;
    Ok(())
}

fn generate_mqtt_module(_config: &DeviceConfig, src_dir: &Path) -> Result<()> {
    let content = r#"//! MQTT client for oasis-cloud communication

use anyhow::Result;
use rumqttc::{AsyncClient, MqttOptions, QoS};
use std::sync::Arc;
use tokio::sync::mpsc;

pub struct MqttHandle {
    pub client: AsyncClient,
    pub tx: mpsc::Sender<MqttMessage>,
}

pub struct MqttMessage {
    pub topic: String,
    pub payload: Vec<u8>,
}

pub async fn start(config: &super::config::AppConfig) -> Result<Arc<MqttHandle>> {
    let mut mqtt_options = MqttOptions::new(
        &config.device_id,
        &config.mqtt.broker,
        config.mqtt.port,
    );
    mqtt_options.set_keep_alive(std::time::Duration::from_secs(30));
    
    if config.mqtt.use_tls {
        // TODO: Configure TLS
    }
    
    let (client, mut eventloop) = AsyncClient::new(mqtt_options, 100);
    
    // Subscribe to command topic
    client.subscribe(&config.mqtt.cmd_topic, QoS::AtLeastOnce).await?;
    
    let (tx, mut rx) = mpsc::channel::<MqttMessage>(100);
    
    // Spawn event loop handler
    tokio::spawn(async move {
        loop {
            tokio::select! {
                event = eventloop.poll() => {
                    match event {
                        Ok(notification) => {
                            tracing::debug!("MQTT: {:?}", notification);
                        }
                        Err(e) => {
                            tracing::error!("MQTT error: {:?}", e);
                        }
                    }
                }
                Some(msg) = rx.recv() => {
                    // Publish outgoing messages
                }
            }
        }
    });
    
    Ok(Arc::new(MqttHandle { client, tx }))
}

pub async fn run(handle: Arc<MqttHandle>) -> Result<()> {
    // Handle incoming commands
    loop {
        tokio::time::sleep(tokio::time::Duration::from_secs(1)).await;
    }
}

pub async fn publish_telemetry(
    handle: &MqttHandle,
    topic: &str,
    payload: &[u8],
) -> Result<()> {
    handle.client.publish(topic, QoS::AtLeastOnce, false, payload).await?;
    Ok(())
}
"#;
    
    fs::write(src_dir.join("mqtt.rs"), content)?;
    Ok(())
}

fn generate_serial_module(_config: &DeviceConfig, src_dir: &Path) -> Result<()> {
    let content = r#"//! Serial bridge for MCU communication

use anyhow::Result;
use tokio_serial::SerialPortBuilderExt;
use std::sync::Arc;

pub struct SerialHandle {
    // Serial port handle
}

pub async fn start(config: &super::config::AppConfig) -> Result<Arc<SerialHandle>> {
    if let Some(serial_config) = &config.serial {
        let port = tokio_serial::new(&serial_config.port, serial_config.baud_rate)
            .open_native_async()?;
        
        tracing::info!("Opened serial port {} at {} baud", 
            serial_config.port, serial_config.baud_rate);
        
        Ok(Arc::new(SerialHandle {}))
    } else {
        Err(anyhow::anyhow!("Serial not configured"))
    }
}

pub async fn run(
    handle: Arc<SerialHandle>,
    mqtt: Arc<super::mqtt::MqttHandle>,
) -> Result<()> {
    // Bridge serial messages to MQTT
    loop {
        // Read from serial
        // Parse message (COBS + MessagePack)
        // Forward to MQTT
        tokio::time::sleep(tokio::time::Duration::from_millis(10)).await;
    }
}
"#;
    
    fs::write(src_dir.join("serial.rs"), content)?;
    Ok(())
}

fn generate_systemd_service(config: &DeviceConfig, output_dir: &Path) -> Result<()> {
    let service_name = config.device.id.replace('-', "_");
    
    let content = format!(r#"[Unit]
Description={device_name} Supervisor
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=oasis
Group=oasis
WorkingDirectory=/opt/oasis/{device_id}
ExecStart=/opt/oasis/{device_id}/{service_name}-supervisor
Restart=always
RestartSec=5
Environment="RUST_LOG=info"

[Install]
WantedBy=multi-user.target
"#,
        device_name = config.device.name,
        device_id = config.device.id,
        service_name = service_name,
    );
    
    fs::write(output_dir.join(format!("{}.service", service_name)), content)?;
    Ok(())
}
