//! Raspberry Pi code generation
//!
//! Generates a Rust supervisor daemon for RPi platforms

use crate::config::*;
use crate::error::Result;
use std::path::Path;
use std::fs;

/// Generate RPi supervisor project
pub fn generate(config: &DeviceConfig, output_dir: &Path) -> Result<()> {
    tracing::info!("Generating RPi supervisor for {}", config.device.id);
    
    // Create output directory structure
    let src_dir = output_dir.join("src");
    fs::create_dir_all(&src_dir)?;
    
    // Generate Cargo.toml
    generate_cargo_toml(config, output_dir)?;
    
    // Generate main.rs
    generate_main_rs(config, &src_dir)?;
    
    // Generate config module
    generate_config_module(config, &src_dir)?;
    
    // Generate sensors module
    generate_sensors_module(config, &src_dir)?;
    
    // Generate actuators module
    generate_actuators_module(config, &src_dir)?;
    
    // Generate MQTT module
    generate_mqtt_module(config, &src_dir)?;
    
    // Generate serial bridge module (for gateway mode)
    generate_serial_module(config, &src_dir)?;
    
    // Generate systemd service file
    generate_systemd_service(config, output_dir)?;
    
    tracing::info!("RPi supervisor generated at {:?}", output_dir);
    Ok(())
}

fn generate_cargo_toml(config: &DeviceConfig, output_dir: &Path) -> Result<()> {
    let content = format!(r#"[package]
name = "{device_id}-supervisor"
version = "0.1.0"
edition = "2021"

[dependencies]
# Async runtime
tokio = {{ version = "1.36", features = ["full"] }}

# GPIO/Hardware
rppal = {{ version = "0.17", features = ["hal"] }}

# MQTT
rumqttc = "0.24"

# HTTP client
reqwest = {{ version = "0.11", features = ["json", "rustls-tls"], default-features = false }}

# Serial communication
tokio-serial = "5.4"

# Serialization
serde = {{ version = "1.0", features = ["derive"] }}
serde_json = "1.0"
postcard = "1.0"

# Logging
tracing = "0.1"
tracing-subscriber = {{ version = "0.3", features = ["env-filter"] }}

# Error handling
anyhow = "1.0"
thiserror = "1.0"

# Config
config = "0.14"
dotenvy = "0.15"

# Time
chrono = "0.4"

[profile.release]
opt-level = 3
lto = true
"#,
        device_id = config.device.id.replace('-', "_"),
    );
    
    fs::write(output_dir.join("Cargo.toml"), content)?;
    Ok(())
}

fn generate_main_rs(config: &DeviceConfig, src_dir: &Path) -> Result<()> {
    let serial_spawn = if matches!(
        config.connectivity.mode,
        ConnectivityMode::Hybrid | ConnectivityMode::SerialGateway
    ) {
        r#"
    // Serial bridge: replaces rusty_pipes.Open child-process management.
    // tokio_serial owns the port; no subprocess, no pid files, no signals.
    let serial_mqtt = Arc::clone(&mqtt);
    let serial_cfg  = Arc::clone(&app_config);
    tokio::spawn(async move {
        if let Err(e) = serial::run(serial_mqtt, &serial_cfg).await {
            tracing::error!("Serial bridge error: {:?}", e);
        }
    });"#
    } else {
        "    // Serial bridge not enabled for this connectivity mode"
    };

    let content = format!(r#"//! {device_name} Supervisor
//!
//! Auto-generated by oasis-build from device.yaml
//! Device ID: {device_id}
//!
//! State sharing: Arc<Mutex<MqttClient>> replaces rusty_pipes fast_mutx JSON-file locks.
//! GPIO ownership: Arc<Gpio> replaces rusty_pins unsendable PyO3 singleton.
//! IPC: MQTT topics replace rusty_pipes.custom_signal JSON file writes.

mod config;
mod sensors;
mod actuators;
mod mqtt;
mod serial;

use anyhow::Result;
use std::sync::Arc;
use tracing::{{info, Level}};
use tracing_subscriber::EnvFilter;

#[tokio::main]
async fn main() -> Result<()> {{
    tracing_subscriber::fmt()
        .with_env_filter(
            EnvFilter::from_default_env()
                .add_directive(Level::INFO.into())
        )
        .init();

    info!("Starting {device_id} supervisor");

    let app_config = Arc::new(config::load()?);
    info!("Loaded configuration for device: {{}}", app_config.device_id);

    // GPIO singleton wrapped in Arc so sensors and actuators share it safely.
    // Replaces rusty_pins #[pyclass(unsendable)] which forced single-threaded access.
    let gpio = Arc::new(rppal::gpio::Gpio::new()?);
    info!("GPIO initialized");

    // MQTT client wrapped in Arc<Mutex<>> replaces rusty_pipes fast_mutx JSON file locking.
    // All modules publish telemetry and receive commands through this single handle.
    let mqtt = mqtt::connect(&app_config).await?;
    info!("MQTT client connected");
{serial_spawn}

    // Run sensors and actuators concurrently — each spawns its own tokio task internally.
    let sensor_gpio   = Arc::clone(&gpio);
    let sensor_mqtt   = Arc::clone(&mqtt);
    let sensor_cfg    = Arc::clone(&app_config);

    let actuator_gpio = Arc::clone(&gpio);
    let actuator_mqtt = Arc::clone(&mqtt);
    let actuator_cfg  = Arc::clone(&app_config);

    tokio::select! {{
        res = sensors::run_all(sensor_gpio, sensor_mqtt, &sensor_cfg) => {{
            if let Err(e) = res {{
                tracing::error!("Sensor task exited: {{:?}}", e);
            }}
        }}
        res = actuators::run_all(actuator_gpio, actuator_mqtt, &actuator_cfg) => {{
            if let Err(e) = res {{
                tracing::error!("Actuator task exited: {{:?}}", e);
            }}
        }}
        _ = tokio::signal::ctrl_c() => {{
            info!("Shutdown signal received");
        }}
    }}

    info!("{device_id} supervisor stopped");
    Ok(())
}}
"#,
        device_name = config.device.name,
        device_id   = config.device.id,
        serial_spawn = serial_spawn,
    );

    fs::write(src_dir.join("main.rs"), content)?;
    Ok(())
}

fn generate_config_module(config: &DeviceConfig, src_dir: &Path) -> Result<()> {
    let content = format!(r#"//! Configuration loading

use anyhow::Result;
use serde::Deserialize;

#[derive(Debug, Deserialize)]
pub struct AppConfig {{
    pub device_id: String,
    pub mqtt: MqttConfig,
    pub https: Option<HttpsConfig>,
    pub serial: Option<SerialConfig>,
}}

#[derive(Debug, Deserialize)]
pub struct MqttConfig {{
    pub broker: String,
    pub port: u16,
    pub use_tls: bool,
    pub telemetry_topic: String,
    pub cmd_topic: String,
}}

#[derive(Debug, Deserialize)]
pub struct HttpsConfig {{
    pub endpoint: String,
    pub batch_interval_s: u32,
}}

#[derive(Debug, Deserialize)]
pub struct SerialConfig {{
    pub port: String,
    pub baud_rate: u32,
}}

pub fn load() -> Result<AppConfig> {{
    // Load .env file if present
    dotenvy::dotenv().ok();
    
    // Build configuration
    let config = AppConfig {{
        device_id: "{device_id}".into(),
        mqtt: MqttConfig {{
            broker: std::env::var("MQTT_BROKER").unwrap_or_else(|_| "{mqtt_broker}".into()),
            port: std::env::var("MQTT_PORT")
                .ok()
                .and_then(|s| s.parse().ok())
                .unwrap_or({mqtt_port}),
            use_tls: {mqtt_tls},
            telemetry_topic: "oasis/devices/{device_id}/telemetry".into(),
            cmd_topic: "oasis/devices/{device_id}/cmd".into(),
        }},
        https: {https_config},
        serial: {serial_config},
    }};
    
    Ok(config)
}}
"#,
        device_id = config.device.id,
        mqtt_broker = config.connectivity.mqtt.as_ref().map(|m| m.broker.as_str()).unwrap_or("localhost"),
        mqtt_port = config.connectivity.mqtt.as_ref().map(|m| m.port).unwrap_or(8883),
        mqtt_tls = config.connectivity.mqtt.as_ref().map(|m| m.use_tls).unwrap_or(true),
        https_config = if config.connectivity.https.is_some() {
            format!(r#"Some(HttpsConfig {{
            endpoint: "{}".into(),
            batch_interval_s: {},
        }})"#, 
                config.connectivity.https.as_ref().unwrap().endpoint,
                config.data_publishing.as_ref()
                    .and_then(|dp| dp.https.as_ref())
                    .map(|h| h.batch_interval_s)
                    .unwrap_or(60)
            )
        } else {
            "None".into()
        },
        serial_config = if config.connectivity.serial.is_some() {
            format!(r#"Some(SerialConfig {{
            port: "/dev/ttyUSB0".into(),
            baud_rate: {},
        }})"#, config.connectivity.serial.as_ref().unwrap().baud_rate)
        } else {
            "None".into()
        },
    );
    
    fs::write(src_dir.join("config.rs"), content)?;
    Ok(())
}

fn sensor_driver_impl(sensor: &Sensor) -> String {
    match sensor.sensor_type {
        SensorType::Dht22 | SensorType::Dht11 => {
            let pin = sensor.pins.data.unwrap_or(4);
            let interval = sensor.sampling.interval_ms;
            format!(r#"
    // {name}: DHT{variant} on GPIO {pin}
    {{
        let name = "{name}".to_string();
        let topic = format!("oasis/devices/{{}}/{name}/telemetry", config.device_id);
        let mqtt = state.clone();
        handles.push(tokio::spawn(async move {{
            loop {{
                // DHT22 uses single-wire protocol via GPIO {pin}
                // rppal does not have native DHT support; read via sysfs or
                // a pre-compiled helper. Emit last known value from shared state.
                let reading = serde_json::json!({{
                    "sensor": name,
                    "temperature_c": null,
                    "humidity_pct": null,
                    "ts": chrono::Utc::now().timestamp_millis(),
                }});
                let _ = mqtt.lock().await.publish(&topic, reading.to_string().into_bytes());
                tokio::time::sleep(tokio::time::Duration::from_millis({interval})).await;
            }}
        }}));
    }}
"#,
                name = sensor.name,
                variant = if sensor.sensor_type == SensorType::Dht22 { "22" } else { "11" },
                pin = pin,
                interval = interval,
            )
        }
        SensorType::Bme280 | SensorType::Bme680 | SensorType::Sht31 => {
            let addr = sensor.i2c_address.unwrap_or(0x76);
            let interval = sensor.sampling.interval_ms;
            format!(r#"
    // {name}: {sensor_type:?} on I2C addr 0x{addr:02X}
    {{
        let name = "{name}".to_string();
        let topic = format!("oasis/devices/{{}}/{name}/telemetry", config.device_id);
        let mqtt = state.clone();
        handles.push(tokio::spawn(async move {{
            let i2c = rppal::i2c::I2c::new().expect("I2C init failed");
            loop {{
                // Read raw bytes from 0x{addr:02X}, parse per datasheet
                let reading = serde_json::json!({{
                    "sensor": name,
                    "i2c_addr": {addr},
                    "ts": chrono::Utc::now().timestamp_millis(),
                }});
                let _ = mqtt.lock().await.publish(&topic, reading.to_string().into_bytes());
                tokio::time::sleep(tokio::time::Duration::from_millis({interval})).await;
            }}
        }}));
    }}
"#,
                name = sensor.name,
                sensor_type = sensor.sensor_type,
                addr = addr,
                interval = interval,
            )
        }
        SensorType::Ds18b20 => {
            let interval = sensor.sampling.interval_ms;
            format!(r#"
    // {name}: DS18B20 1-Wire (reads /sys/bus/w1/devices/)
    {{
        let name = "{name}".to_string();
        let topic = format!("oasis/devices/{{}}/{name}/telemetry", config.device_id);
        let mqtt = state.clone();
        handles.push(tokio::spawn(async move {{
            loop {{
                let temp = tokio::fs::read_dir("/sys/bus/w1/devices/").await
                    .ok()
                    .and_then(|_| None::<f32>); // parse first 28-* device slave file
                let reading = serde_json::json!({{
                    "sensor": name,
                    "temperature_c": temp,
                    "ts": chrono::Utc::now().timestamp_millis(),
                }});
                let _ = mqtt.lock().await.publish(&topic, reading.to_string().into_bytes());
                tokio::time::sleep(tokio::time::Duration::from_millis({interval})).await;
            }}
        }}));
    }}
"#,
                name = sensor.name,
                interval = interval,
            )
        }
        SensorType::CapacitiveMoisture | SensorType::ResistiveMoisture | SensorType::AdcRaw => {
            let pin = sensor.pins.adc.unwrap_or(0);
            let interval = sensor.sampling.interval_ms;
            let debounce = sensor.sampling.averaging.max(1);
            format!(r#"
    // {name}: Analog moisture on ADC channel {pin} (debounce window={debounce})
    // Mirrors rusty_pins.GpioIn debouncing: mode of last {debounce} readings
    {{
        let name = "{name}".to_string();
        let topic = format!("oasis/devices/{{}}/{name}/telemetry", config.device_id);
        let mqtt = state.clone();
        handles.push(tokio::spawn(async move {{
            let mut window: std::collections::VecDeque<f32> = std::collections::VecDeque::with_capacity({debounce});
            loop {{
                // RPi lacks native ADC; read via MCP3008/ADS1115 over SPI/I2C or pigpio
                let raw: f32 = 0.0; // replace with actual ADC read
                if window.len() >= {debounce} {{ window.pop_front(); }}
                window.push_back(raw);
                let avg = window.iter().sum::<f32>() / window.len() as f32;
                let reading = serde_json::json!({{
                    "sensor": name,
                    "adc_channel": {pin},
                    "value": avg,
                    "ts": chrono::Utc::now().timestamp_millis(),
                }});
                let _ = mqtt.lock().await.publish(&topic, reading.to_string().into_bytes());
                tokio::time::sleep(tokio::time::Duration::from_millis({interval})).await;
            }}
        }}));
    }}
"#,
                name = sensor.name,
                pin = pin,
                interval = interval,
                debounce = debounce,
            )
        }
        SensorType::Pir => {
            let pin = sensor.pins.data.unwrap_or(17);
            let interval = sensor.sampling.interval_ms;
            let debounce = sensor.sampling.averaging.max(1) as usize;
            format!(r#"
    // {name}: PIR motion sensor on GPIO {pin} (debounce window={debounce})
    // Mirrors rusty_pins.GpioIn: mode of last {debounce} boolean reads
    {{
        let name = "{name}".to_string();
        let topic = format!("oasis/devices/{{}}/{name}/telemetry", config.device_id);
        let gpio_ref = gpio.clone();
        let mqtt = state.clone();
        handles.push(tokio::spawn(async move {{
            let pin = gpio_ref.get({pin}).expect("GPIO get failed").into_input_pulldown();
            let mut window: std::collections::VecDeque<bool> = std::collections::VecDeque::with_capacity({debounce});
            loop {{
                let high = pin.is_high();
                if window.len() >= {debounce} {{ window.pop_front(); }}
                window.push_back(high);
                let trues = window.iter().filter(|&&v| v).count();
                let motion = trues > window.len() / 2;
                let reading = serde_json::json!({{
                    "sensor": name,
                    "motion": motion,
                    "ts": chrono::Utc::now().timestamp_millis(),
                }});
                let _ = mqtt.lock().await.publish(&topic, reading.to_string().into_bytes());
                tokio::time::sleep(tokio::time::Duration::from_millis({interval})).await;
            }}
        }}));
    }}
"#,
                name = sensor.name,
                pin = pin,
                interval = interval,
                debounce = debounce,
            )
        }
        SensorType::RpiCamera => {
            let interval = sensor.sampling.interval_ms;
            format!(r#"
    // {name}: RPi Camera (libcamera)
    {{
        let name = "{name}".to_string();
        let topic = format!("oasis/devices/{{}}/{name}/telemetry", config.device_id);
        let mqtt = state.clone();
        handles.push(tokio::spawn(async move {{
            loop {{
                // Capture via `libcamera-still -o /tmp/oasis_frame.jpg -n --immediate`
                let output = tokio::process::Command::new("libcamera-still")
                    .args(["-o", "/tmp/oasis_frame.jpg", "-n", "--immediate", "-t", "1"])
                    .output().await;
                let ok = output.map(|o| o.status.success()).unwrap_or(false);
                let reading = serde_json::json!({{
                    "sensor": name,
                    "capture_ok": ok,
                    "path": "/tmp/oasis_frame.jpg",
                    "ts": chrono::Utc::now().timestamp_millis(),
                }});
                let _ = mqtt.lock().await.publish(&topic, reading.to_string().into_bytes());
                tokio::time::sleep(tokio::time::Duration::from_millis({interval})).await;
            }}
        }}));
    }}
"#,
                name = sensor.name,
                interval = interval,
            )
        }
        _ => {
            let interval = sensor.sampling.interval_ms;
            format!(r#"
    // {name}: {sensor_type:?} — generic polling stub
    {{
        let name = "{name}".to_string();
        let topic = format!("oasis/devices/{{}}/{name}/telemetry", config.device_id);
        let mqtt = state.clone();
        handles.push(tokio::spawn(async move {{
            loop {{
                let reading = serde_json::json!({{
                    "sensor": name,
                    "value": null,
                    "ts": chrono::Utc::now().timestamp_millis(),
                }});
                let _ = mqtt.lock().await.publish(&topic, reading.to_string().into_bytes());
                tokio::time::sleep(tokio::time::Duration::from_millis({interval})).await;
            }}
        }}));
    }}
"#,
                name = sensor.name,
                sensor_type = sensor.sensor_type,
                interval = interval,
            )
        }
    }
}

fn generate_sensors_module(config: &DeviceConfig, src_dir: &Path) -> Result<()> {
    let needs_gpio = config.sensors.iter().any(|s| matches!(
        s.sensor_type,
        SensorType::Pir | SensorType::Dht22 | SensorType::Dht11
    ));
    let gpio_import = if needs_gpio {
        "use std::sync::Arc as GpioArc;\nuse rppal::gpio::Gpio;"
    } else {
        "use rppal::gpio::Gpio;"
    };

    let sensor_blocks: String = config.sensors.iter()
        .map(|s| sensor_driver_impl(s))
        .collect();

    let content = format!(r#"//! Sensor drivers — generated from device.yaml
//! Absorbed from legacy rusty_pins: GpioIn debounce pattern → VecDeque window
//! Absorbed from legacy rusty_pipes: subprocess/signal → tokio tasks + MQTT

use anyhow::Result;
{gpio_import}
use tokio::sync::{{Mutex}};
use std::sync::Arc;
use serde_json;
use chrono;

pub struct TelemetrySink {{
    client: Arc<Mutex<super::mqtt::MqttClient>>,
}}

impl TelemetrySink {{
    pub async fn publish(&self, topic: &str, payload: Vec<u8>) -> Result<()> {{
        self.client.lock().await.publish_bytes(topic, payload).await
    }}
}}

pub async fn run_all(
    gpio: Arc<Gpio>,
    state: Arc<Mutex<super::mqtt::MqttClient>>,
    config: &super::config::AppConfig,
) -> Result<()> {{
    let mut handles = Vec::new();
{sensor_blocks}
    for h in handles {{
        h.await.ok();
    }}
    Ok(())
}}
"#,
        gpio_import = gpio_import,
        sensor_blocks = sensor_blocks,
    );

    fs::write(src_dir.join("sensors.rs"), content)?;
    Ok(())
}

fn actuator_driver_impl(actuator: &Actuator) -> String {
    match actuator.actuator_type {
        ActuatorType::Relay | ActuatorType::RelayNc | ActuatorType::Led | ActuatorType::Buzzer => {
            let pin = actuator.pins.output.unwrap_or(0);
            let default_high = matches!(
                actuator.actuator_type,
                ActuatorType::RelayNc // NC relay: default HIGH = coil energised = circuit open
            );
            let initial = if let Some(d) = &actuator.default {
                matches!(d.state, Some(OnOff::On))
            } else {
                default_high
            };
            let watchdog_ms = actuator.safety.as_ref()
                .and_then(|s| s.watchdog_timeout_ms)
                .unwrap_or(0);
            let watchdog_block = if watchdog_ms > 0 {
                format!(r#"
                    // Watchdog: auto-off after {watchdog_ms}ms if no cmd received
                    if last_cmd_ms.elapsed().as_millis() as u64 > {watchdog_ms} {{
                        pin.set_low();
                        tracing::warn!("Watchdog expired for {name}, set LOW");
                    }}
"#, watchdog_ms = watchdog_ms, name = &actuator.name)
            } else {
                String::new()
            };
            format!(r#"
    // {name}: {atype:?} on GPIO {pin} (initial={initial})
    // Mirrors rusty_pins.GpioOut: set_high / set_low via rppal OutputPin
    {{
        let name = "{name}".to_string();
        let cmd_topic = format!("oasis/devices/{{}}/{name}/cmd", config.device_id);
        let gpio_ref = gpio.clone();
        let state_ref = state.clone();
        handles.push(tokio::spawn(async move {{
            let mut pin = gpio_ref.get({pin}).expect("GPIO get").into_output();
            if {initial} {{ pin.set_high(); }} else {{ pin.set_low(); }}
            tracing::info!("Actuator {{}} initialized on GPIO {{}}", name, {pin});
            let mut last_cmd_ms = std::time::Instant::now();
            loop {{
                // Poll command channel for on/off messages
                if let Some(cmd) = state_ref.lock().await.poll_cmd(&cmd_topic) {{
                    match cmd.as_str() {{
                        "on"  => {{ pin.set_high(); last_cmd_ms = std::time::Instant::now(); }}
                        "off" => {{ pin.set_low();  last_cmd_ms = std::time::Instant::now(); }}
                        _     => tracing::warn!("Unknown cmd {{}} for {{}}", cmd, name),
                    }}
                }}
                {watchdog_block}
                tokio::time::sleep(tokio::time::Duration::from_millis(50)).await;
            }}
        }}));
    }}
"#,
                name = actuator.name,
                atype = actuator.actuator_type,
                pin = pin,
                initial = initial,
                watchdog_block = watchdog_block,
            )
        }
        ActuatorType::Pwm | ActuatorType::Servo => {
            let pin = actuator.pins.pwm.unwrap_or(actuator.pins.output.unwrap_or(0));
            let min_v = actuator.constraints.as_ref().and_then(|c| c.min_value).unwrap_or(0);
            let max_v = actuator.constraints.as_ref().and_then(|c| c.max_value).unwrap_or(1000);
            format!(r#"
    // {name}: {atype:?} on GPIO {pin} (PWM, range {min_v}–{max_v})
    {{
        let name = "{name}".to_string();
        let cmd_topic = format!("oasis/devices/{{}}/{name}/cmd", config.device_id);
        let gpio_ref = gpio.clone();
        let state_ref = state.clone();
        handles.push(tokio::spawn(async move {{
            let mut pin = gpio_ref.get({pin}).expect("GPIO get").into_output();
            let mut current_duty: f64 = 0.0;
            loop {{
                if let Some(cmd) = state_ref.lock().await.poll_cmd(&cmd_topic) {{
                    if let Ok(v) = cmd.parse::<u16>() {{
                        let clamped = v.clamp({min_v}, {max_v});
                        current_duty = clamped as f64 / {max_v} as f64;
                        // Software PWM: set_pwm via rppal::pwm or bit-bang via OutputPin
                        tracing::info!("{{}} duty={{:.2}}", name, current_duty);
                    }}
                }}
                tokio::time::sleep(tokio::time::Duration::from_millis(20)).await;
            }}
        }}));
    }}
"#,
                name = actuator.name,
                atype = actuator.actuator_type,
                pin = pin,
                min_v = min_v,
                max_v = max_v,
            )
        }
        _ => {
            let pin = actuator.pins.output
                .or(actuator.pins.pwm)
                .or(actuator.pins.step)
                .unwrap_or(0);
            format!(r#"
    // {name}: {atype:?} on GPIO {pin} — generic digital stub
    {{
        let name = "{name}".to_string();
        let cmd_topic = format!("oasis/devices/{{}}/{name}/cmd", config.device_id);
        let gpio_ref = gpio.clone();
        let state_ref = state.clone();
        handles.push(tokio::spawn(async move {{
            let mut pin = gpio_ref.get({pin}).expect("GPIO get").into_output();
            loop {{
                if let Some(cmd) = state_ref.lock().await.poll_cmd(&cmd_topic) {{
                    match cmd.as_str() {{
                        "on"  => pin.set_high(),
                        "off" => pin.set_low(),
                        _     => {{}},
                    }}
                }}
                tokio::time::sleep(tokio::time::Duration::from_millis(50)).await;
            }}
        }}));
    }}
"#,
                name = actuator.name,
                atype = actuator.actuator_type,
                pin = pin,
            )
        }
    }
}

fn generate_actuators_module(config: &DeviceConfig, src_dir: &Path) -> Result<()> {
    let actuator_blocks: String = config.actuators.iter()
        .map(|a| actuator_driver_impl(a))
        .collect();

    let content = format!(r#"//! Actuator drivers — generated from device.yaml
//! Absorbed from legacy rusty_pins: GpioOut set_high/set_low → rppal 0.17 OutputPin
//! Watchdog pattern replaces rusty_pipes fast_mutx JSON-file locking

use anyhow::Result;
use rppal::gpio::Gpio;
use tokio::sync::Mutex;
use std::sync::Arc;

pub async fn run_all(
    gpio: Arc<Gpio>,
    state: Arc<Mutex<super::mqtt::MqttClient>>,
    config: &super::config::AppConfig,
) -> Result<()> {{
    let mut handles = Vec::new();
{actuator_blocks}
    for h in handles {{
        h.await.ok();
    }}
    Ok(())
}}
"#,
        actuator_blocks = actuator_blocks,
    );

    fs::write(src_dir.join("actuators.rs"), content)?;
    Ok(())
}

fn generate_mqtt_module(config: &DeviceConfig, src_dir: &Path) -> Result<()> {
    let _device_id = &config.device.id;
    let broker = config.connectivity.mqtt.as_ref()
        .map(|m| m.broker.as_str()).unwrap_or("localhost");
    let port = config.connectivity.mqtt.as_ref()
        .map(|m| m.port).unwrap_or(8883);

    // Collect all actuator command topics so we subscribe to them on connect
    let cmd_topic_subs: String = config.actuators.iter().map(|a| {
        format!(
            "    client.subscribe(format!(\"oasis/devices/{{}}/{name}/cmd\", device_id), QoS::AtLeastOnce).await?;\n",
            name = a.name,
        )
    }).collect();

    let content = format!(r#"//! MQTT client — generated from device.yaml
//! Absorbed from legacy rusty_pipes.custom_signal: JSON-file IPC → MQTT topics
//! Absorbed from legacy rusty_pipes.fast_mutx: JSON-file mutex → tokio channel cmd queue

use anyhow::{{Context, Result}};
use rumqttc::{{AsyncClient, Event, MqttOptions, Packet, Publish, QoS}};
use tokio::sync::{{mpsc, Mutex}};
use std::{{collections::HashMap, sync::Arc}};

/// Commands received from oasis-cloud, keyed by topic.
/// Replaces rusty_pipes.custom_signal JSON file signals and fast_mutx locks —
/// MQTT topics are the coordination primitive, tokio channels are the mutex.
type CmdQueue = Arc<Mutex<HashMap<String, Vec<String>>>>;

/// Shared MQTT client used by sensors.rs, actuators.rs, and serial.rs.
/// Wraps rumqttc AsyncClient + an inbound command queue.
pub struct MqttClient {{
    client: AsyncClient,
    cmd_queue: CmdQueue,
    device_id: String,
}}

impl MqttClient {{
    /// Publish raw bytes to a topic (telemetry path for sensors/serial)
    pub async fn publish_bytes(&self, topic: &str, payload: Vec<u8>) -> Result<()> {{
        self.client
            .publish(topic, QoS::AtLeastOnce, false, payload)
            .await
            .context("MQTT publish failed")
    }}

    /// Publish a JSON-serializable value as telemetry
    pub async fn publish(&self, topic: &str, payload: Vec<u8>) -> Result<()> {{
        self.publish_bytes(topic, payload).await
    }}

    /// Drain one command for the given topic (non-blocking).
    /// Replaces rusty_pipes fast_mutx lock/unlock — caller owns the value once dequeued.
    pub async fn poll_cmd(&self, topic: &str) -> Option<String> {{
        self.cmd_queue.lock().await
            .get_mut(topic)
            .and_then(|q| if q.is_empty() {{ None }} else {{ Some(q.remove(0)) }})
    }}
}}

/// Connect to MQTT, subscribe to all actuator cmd topics, and return a shared client.
pub async fn connect(config: &super::config::AppConfig) -> Result<Arc<Mutex<MqttClient>>> {{
    let device_id = config.device_id.clone();
    let mut opts = MqttOptions::new(&device_id, "{broker}", {port});
    opts.set_keep_alive(std::time::Duration::from_secs(30));
    opts.set_clean_session(true);

    let (client, mut eventloop) = AsyncClient::new(opts, 128);

    // Subscribe to all actuator command topics
{cmd_topic_subs}
    tracing::info!("MQTT connecting to {broker}:{port} as {{}}", device_id);

    let cmd_queue: CmdQueue = Arc::new(Mutex::new(HashMap::new()));
    let queue_ref = cmd_queue.clone();

    // Event loop: drive rumqttc and funnel inbound Publish packets into cmd_queue.
    // Replaces rusty_pipes.custom_signal + fast_mutx: no JSON files, no fs::write races.
    tokio::spawn(async move {{
        loop {{
            match eventloop.poll().await {{
                Ok(Event::Incoming(Packet::Publish(Publish {{ topic, payload, .. }}))) => {{
                    let val = String::from_utf8_lossy(&payload).trim().to_string();
                    tracing::debug!("CMD {{}}: {{}}", topic, val);
                    queue_ref.lock().await
                        .entry(topic.to_string())
                        .or_default()
                        .push(val);
                }}
                Ok(Event::Incoming(Packet::ConnAck(_))) => {{
                    tracing::info!("MQTT connected");
                }}
                Ok(_) => {{}}
                Err(e) => {{
                    tracing::error!("MQTT error: {{:?}}", e);
                    tokio::time::sleep(tokio::time::Duration::from_secs(5)).await;
                }}
            }}
        }}
    }});

    Ok(Arc::new(Mutex::new(MqttClient {{
        client,
        cmd_queue,
        device_id,
    }})))
}}
"#,
        broker = broker,
        port = port,
        cmd_topic_subs = cmd_topic_subs,
    );

    fs::write(src_dir.join("mqtt.rs"), content)?;
    Ok(())
}

fn generate_serial_module(config: &DeviceConfig, src_dir: &Path) -> Result<()> {
    let baud = config.connectivity.serial.as_ref()
        .map(|s| s.baud_rate)
        .unwrap_or(115200);
    let protocol = config.connectivity.serial.as_ref()
        .map(|s| s.protocol)
        .unwrap_or_default();
    let framing_comment = match protocol {
        SerialProtocol::CobsMsgpack => "COBS-framed MessagePack",
        SerialProtocol::CobsJson    => "COBS-framed JSON",
        SerialProtocol::RawJson     => "newline-delimited JSON",
    };

    let content = format!(r#"//! Serial bridge — generated from device.yaml
//! Absorbed from legacy rusty_pipes.Open: managed child process → tokio_serial async task
//! Absorbed from legacy rusty_pipes.custom_signal: JSON file signals → MQTT cmd topics
//! Framing: {framing_comment}

use anyhow::{{Context, Result}};
use tokio_serial::{{SerialPortBuilderExt, SerialStream}};
use tokio::io::{{AsyncReadExt, AsyncWriteExt, BufReader}};
use tokio::sync::Mutex;
use std::sync::Arc;

/// Decoded message from an MCU minion over serial
#[derive(Debug, serde::Deserialize)]
pub struct MinonMessage {{
    pub source: Option<String>,
    pub kind: Option<String>,
    pub payload: serde_json::Value,
}}

/// Open the serial port and bridge minion telemetry → MQTT
/// Replaces rusty_pipes.Open subprocess wrapper: the port is owned by this async task,
/// no child process needed. Shutdown is via tokio cancellation token / ctrl-c.
pub async fn run(
    mqtt: Arc<Mutex<super::mqtt::MqttClient>>,
    config: &super::config::AppConfig,
) -> Result<()> {{
    let serial_cfg = config.serial.as_ref()
        .context("Serial not configured but serial bridge was spawned")?;

    let port = tokio_serial::new(&serial_cfg.port, {baud})
        .open_native_async()
        .with_context(|| format!("Failed to open {{}}", &serial_cfg.port))?;
    tracing::info!("Serial bridge open: {{}} @ {baud} baud", &serial_cfg.port);

    let mut reader = BufReader::new(port);
    let mut frame_buf = Vec::with_capacity(256);

    loop {{
        // Read until newline (RawJson) or COBS end-of-frame (0x00)
        let delimiter: u8 = {delimiter};
        match reader.read_until_byte(delimiter, &mut frame_buf).await {{
            Ok(0) => {{
                tracing::warn!("Serial EOF — MCU disconnected?");
                tokio::time::sleep(tokio::time::Duration::from_secs(2)).await;
                frame_buf.clear();
                continue;
            }}
            Ok(_) => {{}}
            Err(e) => {{
                tracing::error!("Serial read error: {{:?}}", e);
                frame_buf.clear();
                continue;
            }}
        }}

        // Decode frame
        let payload_bytes = frame_buf.trim_ascii();
        let msg: Result<MinonMessage, _> = serde_json::from_slice(payload_bytes);
        frame_buf.clear();

        match msg {{
            Ok(m) => {{
                let topic = format!(
                    "oasis/devices/{{}}/minion/{{}}/telemetry",
                    config.device_id,
                    m.source.as_deref().unwrap_or("unknown"),
                );
                let json = serde_json::to_vec(&m.payload).unwrap_or_default();
                if let Err(e) = mqtt.lock().await.publish_bytes(&topic, json).await {{
                    tracing::warn!("MQTT publish failed: {{:?}}", e);
                }}
            }}
            Err(e) => {{
                tracing::debug!("Serial frame parse error: {{:?}}", e);
            }}
        }}
    }}
}}
"#,
        framing_comment = framing_comment,
        baud = baud,
        delimiter = match protocol {
            SerialProtocol::RawJson  => 0x0Au8, // '\n'
            _                        => 0x00u8, // COBS end-of-frame
        },
    );

    fs::write(src_dir.join("serial.rs"), content)?;
    Ok(())
}

fn generate_systemd_service(config: &DeviceConfig, output_dir: &Path) -> Result<()> {
    let service_name = config.device.id.replace('-', "_");
    
    let content = format!(r#"[Unit]
Description={device_name} Supervisor
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=oasis
Group=oasis
WorkingDirectory=/opt/oasis/{device_id}
ExecStart=/opt/oasis/{device_id}/{service_name}-supervisor
Restart=always
RestartSec=5
Environment="RUST_LOG=info"

[Install]
WantedBy=multi-user.target
"#,
        device_name = config.device.name,
        device_id = config.device.id,
        service_name = service_name,
    );
    
    fs::write(output_dir.join(format!("{}.service", service_name)), content)?;
    Ok(())
}
